#!/bin/sh

trap 'exit 0' INT

repositories=$(gh repo list --json name --jq '.[].name')

for repo in $repositories; do
    if [ -d "${repo}" ]; then
        repositories=$(echo "$repositories" | sed -e "s/$repo//g" | sed -e '/^$/d')
    fi
done

selected_repo=$(echo "$repositories" | tr ' ' '\n' | fzf)

if [ -n "$selected_repo" ]; then
    gh repo clone "$selected_repo"
fi

